### ISSUE TITLE
Проверка на приличность.

### ISSUE THREAD

**Issue by bonvech** [VanDarakHome/TextQuest#1]
Проверь, можно ли этот контент маркировать как 10+.

**Comment by bonvech** [comment]
Проконсультируйся с родителями.

**Comment by VanDarakHome** [comment]
Ваш отзыв очень важен для нас! Мы сделали все возможное чтобы соответствовать вашим требованиям и даже выполнили вашу просьбу! С уважением команда VanDarakHome!

**Comment by VanDarakHome** [comment]
С уважением команда VanDarakHome
