### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by AlexeyTheWarthunder** [VanDarakHome/TextQuest#2]
В моменте, где наша легенда приходит в ломбард и на Вопрос "Есть ли у вас что-то еще" отвечает да, а потом втюхивает ломбардщику видеокарту, можно зациклить программу

**Comment by VanDarakHome** [comment]
Данный отзыв очень важен для нас! Мы починили все глюки которые смогли найти в системе. Спасибо за связь с нами, удачи в боях боец!
